version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ateliertt
      POSTGRES_USER: atelier
      POSTGRES_PASSWORD: S3cret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ateliertt
      SPRING_DATASOURCE_USERNAME: atelier
      SPRING_DATASOURCE_PASSWORD: S3cret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pgdata: